-- DDL generated by DBeaver CE
-- WARNING: It may differ from actual native database DDL
CREATE TABLE inventory.mainapp_userprofile (
	id bigint(20) NULL,
	Usergroup_id int(11) NULL,
	user_id int(11) NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;