# Generated by Django 5.1.7 on 2025-05-25 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='warehouse',
            field=models.ForeignKey(blank=True, db_column='Warehouse_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.warehouse'),
        ),
        migrations.AddField(
            model_name='users',
            name='usergroup',
            field=models.ForeignKey(blank=True, db_column='Usergroup_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.usergroups'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='usergroup',
            field=models.ForeignKey(blank=True, db_column='Usergroup_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.usergroups'),
        ),
    ]
